### ISSUE TITLE
Source code build fails

### ISSUE THREAD

**Issue by karuppiah7890** [sorintlab/stolon#585]
### Submission type

 - Bug report

### Environment

Mac OS 10.13.6
go version go1.11.2 darwin/amd64

#### Stolon version

commit `2536d50fb9d86479ee39260093a76b97186216be`

### Bug Report

I ran this to build code

```
./build
```

### Expected behaviour you didn't see

Binaries in the `bin` directory

### Unexpected behaviour you saw

Saw these errors

```
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:36:10: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:37:10: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:40:44: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:41:30: undefined: v1alpha1.ExternalAdmissionHookConfigurationList
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:43:87: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:60:96: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:72:82: undefined: v1alpha1.ExternalAdmissionHookConfigurationList
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:92:90: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:103:90: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:135:132: undefined: v1alpha1.ExternalAdmissionHookConfiguration
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/admissionregistration/v1alpha1/externaladmissionhookconfiguration.go:135:132: too many errors
# k8s.io/client-go/kubernetes/typed/extensions/v1beta1
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:36:10: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:37:10: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:40:44: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:41:30: undefined: v1beta1.ThirdPartyResourceList
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:43:87: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:60:80: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:72:66: undefined: v1beta1.ThirdPartyResourceList
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:92:58: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:103:58: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:135:116: undefined: v1beta1.ThirdPartyResource
../../../../../go/pkg/mod/k8s.io/client-go@v0.0.0-20171026121518-35ccd4336052/kubernetes/typed/extensions/v1beta1/thirdpartyresource.go:135:116: too many errors
```

### Steps to reproduce the problem

Clone the code. Git checkout to commit `2536d50fb9d86479ee39260093a76b97186216be`. Run `./build`

**Comment by sgotti** [comment]
@karuppiah7890 Sorry but I cannot reproduce this issue and also travis CI that builds with both go 1.10.x (using vendored packages) and go 1.11.2 (using go modules without vendor) fetches and builds the dependencies correctly (https://travis-ci.org/sorintlab/stolon/builds/452372679). We only build and use GNU/Linux so I'm not sure if it could be a Mac OS issue.

You could try doing a `go mod verify` to check that you mod cache is good or try cleaning up you go mod cache (`~/go/pkg/mod). If you just need to build it you can just disable modules putting your source in the `$GOPATH`.

**Comment by karuppiah7890** [comment]
Yes, I missed cleaning up my go mod cache this time. It worked after deleting the `~/go/pkg/mod` directory. DIdn't have to move the source code to `$GOPATH`
