### PR TITLE
*: update to latest uber-go/zap

### PR DESCRIPTION
**Pull request by sgotti**
A lot of things have changed in uber-go/zap and now its interface is
marked as stable.

### CODE REVIEW

**Comment by JGroselle** [comment]
Hi @sgotti Changing uber-go/zap version add some requirements to stolon.
As https://github.com/uber-go/zap/issues/389 it is not possible to build on Ubuntu LTS16.04.
```
$ go version
go version go1.6.2 linux/amd64
```

Here is my output:
```
ubuntu@pg-sentinel:~/stolon$ ./build
# github.com/sorintlab/stolon/vendor/go.uber.org/zap
gopath/src/github.com/sorintlab/stolon/vendor/go.uber.org/zap/stacktrace.go:63: undefined: runtime.CallersFrames
ubuntu@pg-sentinel:~/stolon$ l bin/
ubuntu@pg-sentinel:~/stolon$ git checkout tags/v0.6.0
Previous HEAD position was fec5140... Release v0.7.0
HEAD is now at 8420cb1... Release v0.6.0
ubuntu@pg-sentinel:~/stolon$ ./build
ubuntu@pg-sentinel:~/stolon$ l bin/
stolonctl*  stolon-keeper*  stolon-proxy*  stolon-sentinel*
```

You should update dependencies by adding Go >=1.7.
